Use vanilla Kubernetes manifests for Rancher (replacing Route et al.)
painless-software/painless-continuous-delivery pull request #175
Opened 2020-09-03 13:52 UTC by bittner

The changes herein will allow to generate a [vanilla Kubernetes](https://kubernetes.io/) deployment configuration, one that is usable with a [Rancher cluster](https://rancher.com/) (as opposed to [OpenShift v3](https://www.openshift.com/), which was exclusively targeted / supported until now).

2020-09-08 08:08 UTC, chamer81 requested changes
The test failures are caused by the following problems:

The Bandit test fails due to a security issue, see: https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html
Essentially the "Shell" class (in post_gen_project.py) is vulnerable to shell injection. If we are OK with this risk, then we should add an exception for bandit to ignore this problem.

The Behave tests are failing on Travis CI because the tox environment is somehow not able to install Kustomize:
`When I generate the deployment configuration         # tests/acceptance/steps/when.py:28 0.223s

      Assertion Failed: Command failed with error:

      Binary for kustomize not found. Attempting download ...

      Downloading https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.8.2/kustomize_v3.8.2_linux_amd64.tar.gz ...

      Extracting from /tmp/tmpch27hkwikustomize_v3.8.2_linux_amd64.tar.gz: /home/travis/build/painless-software/painless-continuous-delivery/.tox/behave/local/bin/kustomize

      Extracting binary failed: file could not be opened successfully

      Try installing in --user space.`

The kustomize-wrapper is included in the kubernetes installdeps, but there seems to be some problem getting the actual binary. I'm not sure what the problem is -- the binary that is referenced in the above error message does exist. Maybe there's not enough space in the Travis CI runner to extract it....?

Anyway, I think we should clean up these test problems because when the test are showing as red, it's hard to identify new problems that may arise.

2020-09-08 10:14 UTC, bittner commented
Argh, @chamer81, that's a new problem. and this is totally Travis CI specific. :worried: It could be that this is really a temporary Travis infrastructure issue BECAUSE the second Travis job actually _succeeds_. Very weird. I'll retrigger the failed build to see if this fixes the problem.

2020-09-08 10:19 UTC, bittner commented
That fixed it. It was a Travis infrastructure hickup.

We now only need the Kubernetes manifests added to this PR, then we can merge it. @ZuGao please! :rocket:

2020-09-08 10:49 UTC, soufianebenali commented
LGTM

2020-09-08 10:49 UTC, soufianebenali approved these changes

2020-09-08 13:34 UTC, chamer81 approved these changes
Looks good, thanks for fixing the tests!

2020-09-09 13:09 UTC, ZuGao commented
Updated the manifests to work properly with springboot and flux

2020-09-10 09:24 UTC, bittner commented on cookiecutter.json
> +    "flux_ssh_known_hosts": "",
@ZuGao This is not in use yet. I'll remove it for this PR to make sense to be merged.

You can still add it later, but I'd suggest to use a more generic naming (something with "gitops" maybe) or have this added in some other way.

2020-09-10 09:30 UTC, bittner commented on {{cookiecutter.project_slug}}/_/frameworks/SpringBoot/pom.xml
> +        </dependency>
As explained by @ZuGao yesterday, this is a useful addition to the Spring Boot setup to easily provide health check endpoints for the Kubernetes deployment configuration.

Noteworthy to remember for all of us! :point_up:

2020-09-10 09:34 UTC, bittner commented on {{cookiecutter.project_slug}}/deployment/application/base/deployment.yaml
> +          {%- endif %}
Just as a heads-up: We need to refactor this part.

1. Health checks (probes) should be generic, implemented for all frameworks.
1. This has nothing to do with "uwsgi" specifically here (only with Python).

2020-09-10 10:04 UTC, merged